# --------- Support -----------

# https://www.spigotmc.org/resources/disablecommands-1-13-x-1-20-x.110823/

# --------- Permissions -----------

# "disablecommands.*": Grants complete access to the plugin.
# "disablecommands.manage": Allows adding and removing disabled commands.
# "disablecommands.list": Allows printing the list of disabled commands.
# "disablecommands.reload": Allows reloading the DisableCommands plugin.
# "disablecommands.bypass.*": Allows bypassing all disabled commands.
# "disablecommands.bypass.<command>": Allows bypassing a specific disabled command.

# --------- Config -----------

# Disable all commands
disable_all: false

# Message for disabled commands
disable_message: '&cThis command is disabled'

# Message for commands that does not exist
no_exist_message: "&cThe command doesn't exist."

# Message for players without permission
# {perm} is replaced by the permission
no_permission_message: "&cYou don't have the permission &e{perm}"

# List of disabled commands
disable_commands:
  - '?'
  - 'plugins'
  - 'pl'
  - 'help'